### ISSUE TITLE
保存布尔值不成功，isLogout其实是个Bool的number类型。

### ISSUE THREAD

**Issue by huangping35** [netyouli/WHC_ModelSqliteKit#11]
[WHC_ModelSqlite update:info where:[NSString stringWithFormat:@"isLogout=%@",@(YES)]]; 或者  [WHC_ModelSqlite update:info where:[NSString stringWithFormat:@"isLogout = %@ AND CustomerId = %@",@(YES),info.CustomerId]]; 这个保存不成功，

**Comment by netyouli** [comment]
不是保存不成功是你update的where写的不对所以更新不了

**Comment by huangping35** [comment]
@netyouli  那要怎么写才正确？

**Comment by netyouli** [comment]
请更新版本再试，并且支持复杂多表字段嵌套查询例如：NSArray * personArray = [WHC_ModelSqlite query:[Person class]
                                             where:@"name = '吴海超' and car.name = '宝马' or school.city.name = '北京'"];

**Comment by huangping35** [comment]
@netyouli  还是不行，isLogout 还是保存不成功

**Comment by netyouli** [comment]
参考demo，demo里有存储bool值得

**Comment by huangping35** [comment]
@netyouli  update整个对象就行，不写那个where

**Comment by netyouli** [comment]
那是你where条件写错了，根本没更新

**Comment by netyouli** [comment]
[WHC_ModelSqlite update:info where:[NSString stringWithFormat:@"isLogout=%@",@(YES)]]; 或者 [WHC_ModelSqlite update:info where:[NSString stringWithFormat:@"isLogout = %@ AND CustomerId = %@",@(YES),info.CustomerId]];这个保存不成功，
哥们你这个where很明显是错误，sql的where语法你好好百度学习一下

**Comment by netyouli** [comment]
不是你想当然的写和oc是不一样的

**Comment by huangping35** [comment]
@netyouli  受教了，谢谢。这个让我突然怀念coredata。

**Comment by huangping35** [comment]
@netyouli  可以了，能把数据库的存放路径开放出来吗，cocoapods不方便。

**Comment by netyouli** [comment]
路径放开，自动管理数据库版本不方便，这个下个版本再考虑考虑
