### ISSUE TITLE
两个小小问题

### ISSUE THREAD

**Issue by ekingo** [netyouli/WHC_ModelSqliteKit#13]
1，[local_model_name rangeOfString:version].location == NSNotFound，这里判断版本号的地方，是否有问题？比如1.0版本升级到1.0.1有多位字母表示的版本号，以及1.0版本升级到11.0版本时呢？直接字符串去比较版本号是否更合理？

2，数据库每次增删改查都是打开数据库，然后关闭，是否会有效率方面的影响？可否数据按ModelClass来建多张表到一个数据库里，打开一次，多个数据表公用一个数据库，而不是建立多个文件呢？

以上！

**Comment by netyouli** [comment]
1，是比较字符串版本号不是比大小
2，在插入数组对象是事务，每次操作完成就结束，能有利于内存释放，实际开发我们也是操作玩了就关闭数据库

**Comment by ekingo** [comment]
1，确实没有问题，字符串比较就是只要版本号有增加了都是认为有新版本的，1.0.0版本与1.0版本是不同的。

**Comment by netyouli** [comment]
至于为什么一个classmodel搞一个数据库主要是为了管你方便好处理版本号，然后再考虑到sqlite是单线程一次只能操作一个表所以我这样的设计方式和一个数据库多个表性能上基本上一致的，可能就是增加了几个数据库文件但是这样便于查看和管理

**Comment by ekingo** [comment]
了解了，多些指教！
