### ISSUE TITLE
几处改动（扩展）

### ISSUE THREAD

**Issue by ekingo** [netyouli/WHC_ModelSqliteKit#14]
1，定义的Model支持继承
`
- (NSDictionary *)parserModelObjectFieldsWithModelClass:(Class)modelClass {
    if (modelClass == [NSObject class]) {
        //如果是NSObject，则意味着还没有定义字段
        return nil;
    }
    
    NSMutableDictionary * fields = [NSMutableDictionary dictionary];
    unsigned int property_count = 0;
    objc_property_t * propertys = class_copyPropertyList(modelClass, &property_count);

        }
    }
    free(propertys);
    
    if (modelClass.superclass) {
        NSDictionary *fieldSuper = [self parserModelObjectFieldsWithModelClass:modelClass.superclass];
        [fieldSuper enumerateKeysAndObjectsUsingBlock:^(id key,id obj,BOOL *stop){
            [fields setValue:obj forKey:key];
        }];
    }
    
    return fields;
}
`

2，对NSArray之类的数据也支持保存，
`
else if (class_type == [NSArray class] ||
                       class_type == [NSDictionary class] ||
                       class_type == [NSDate class] ||
                       class_type == [NSSet class] ||
                       class_type == [NSValue class]) {

                NSLog(@"检查模型类异常数据类型(不支持类型：%@)[自定义类型需要实现encodeWithCoder/initWithCoder",class_type);

                WHC_PropertyInfo * property_info = [[WHC_PropertyInfo alloc] initWithType:_Blob propertyName:property_name_string];

                [fields setObject:property_info forKey:property_name_string];

            }
`

3，对于定义的NSString类型，做强制判断，
`
case _String: {
                    NSString * value = [model valueForKey:field];
                    id value = [model valueForKey:field];
                    if (value == nil) {
                        value = @"";
                    }
                    if (![value isKindOfClass:[NSString class]]) {
                        if ([value respondsToSelector:@selector(stringValue)]) {
                            value = [value stringValue];
                        }else{
                            NSLog(@"value:%@ is not NSString!!!(save value as empty string)",value);
                            break;
                        }
                    }
                    iResult = sqlite3_bind_text(pp_stmt, index, [value UTF8String], -1, SQLITE_TRANSIENT);
                }
                    break;
`

4，可自动扩展模型字段alter数据表，在创建数据表时，先判断是否已存在，然后自动重新解析字段
`//首先判断数据表是否已存在，是否需要更新字段
        if ([self isTableExists:tableName]) {
            //更新字段
            NSLog(@"table:%@ has existed",tableName);
            
            bRes = [self alterTable:tableName fields:fields];
            break;
        }`

5，使用了FMDB/SQLCiper对数据库可加密处理；

6，在query数据之前，先判断是否存在文件，如果不存在，不自动创建数据表。

7，支持联合主键unionPrimaryKey，插入数据库时，先判断是否有主键，
`
- (NSString *)primaryKeyWhereSQLForModel:(id)model{
    NSMutableString *sql = [NSMutableString stringWithString:@""];
    
    NSArray *primaryKeys = [self performFunc:kUnionPrimaryKeys forClass:[model class]];
    if ([primaryKeys count]>0) {
        for (NSString *key in primaryKeys) {
            id value = [model valueForKey:key];
            //TODO:value需要做类型判断以及转换
            if (value) {
                if (sql.length>0) {
                    [sql appendString:@" and "];
                }
                
                [sql appendString:[NSString stringWithFormat:@"%@=\'%@\'",key,value]];
            }
        }
    }
    
    return sql;
}
`

以上主要改动的地方，多谢作者提供的该库；

**Comment by netyouli** [comment]
恩不错，近期本人也会对该库进行重大升级，敬请关注

**Comment by robinyue** [comment]
期待下次更新

**Comment by netyouli** [comment]
已经更新了
