### ISSUE TITLE
insert成功或失败没返回值吗？

### ISSUE THREAD

**Issue by wangchangfei** [netyouli/WHC_ModelSqliteKit#15]
insert成功或失败没返回值吗？

**Comment by netyouli** [comment]
新版本有返回值
请更新版本再试，并且支持复杂多表字段嵌套查询例如：NSArray * personArray = [WHC_ModelSqlite query:[Person class]
                                             where:@"name = '吴海超' and car.name = '宝马' or school.city.name = '北京'"];
