### ISSUE TITLE
deleteModel后在insertsModel后，subModel查询为null

### ISSUE THREAD

**Issue by LeeFengHY** [netyouli/WHC_ModelSqliteKit#16]
如果我把表里面的数据delete后，再往里面添加数据，新数据的主建key值是在原来的数据key值+1的，而subModel的sub_id还是从1开始导致连表查询subModel有些值为null。

**Comment by netyouli** [comment]
你说你是手动把表数据删除，然后用我库api插入？你如果要手动删除那么也要把与其关联的子表也要删除
