### ISSUE TITLE
insert速度太慢

### ISSUE THREAD

**Issue by hellozhjxl** [netyouli/WHC_ModelSqliteKit#17]
插入上千条数据就耗时10s左右,不明白为什么会这么慢,改用fmdb开启事务毫秒完成.
而且每个类都创建了一个数据库,感觉不太合理,创建表即可,为什么要创建数据库?

**Comment by netyouli** [comment]
用inserts api存批量

**Comment by netyouli** [comment]
关于插入慢的问题已经找到并且修复了，请更新版本再试，并且支持复杂多表字段嵌套查询例如：NSArray * personArray = [WHC_ModelSqlite query:[Person class]
                                             where:@"name = '吴海超' and car.name = '宝马' or school.city.name = '北京'"];
