### ISSUE TITLE
请问有没有简单的修改查找到模型其中的一个属性，其他属性不变的方法呢

### ISSUE THREAD

**Issue by ljw215** [netyouli/WHC_ModelSqliteKit#18]
请问有没有简单的修改查找到模型其中的一个属性，其他属性不变的方法呢

**Comment by netyouli** [comment]
这个库已经做的很简单了，真正一行代码完成数据库操作，具体可以参考提供的demo示例

**Comment by BaiHan1989** [comment]
update 能不能根据条件去更新，不要更新其他字段

**Comment by netyouli** [comment]
where不是条件吗

**Comment by BaiHan1989** [comment]
我想根据where 修改特定的字段内容

**Comment by BaiHan1989** [comment]
我的意思是 比如说我想如果age > 25，isStudent 为 NO

**Comment by netyouli** [comment]
更新某个字段值目前api不支持，耐心等我更新吧

**Comment by netyouli** [comment]
新版本已经支持这个问题：
// 更新整条记录中指定的字段(更新Person表在age字段大于25岁时name值为whc，age为100岁)
    BOOL result = [WHCSqlite update:Person.self value:@"name = 'whc', age = 100"
                              where:@"age > 25"];
