### ISSUE TITLE
查询的时候能限制查询条数吗？

### ISSUE THREAD

**Issue by heyehao2008** [netyouli/WHC_ModelSqliteKit#2]
看查询只有用where条件语句。像一个tableView的数据，每次查询20条，要怎么做呢？这个好像不支持

**Comment by heyehao2008** [comment]
哦，可以用sql语句的limit来限制。希望该库更加完善，谢谢作者的无私奉献。操作数据库从来没有如此清爽简单

**Comment by heyehao2008** [comment]
希望可以增加一个方法来处理这种情况：某类中有一些property不需要创建数据库字段。

**Comment by heyehao2008** [comment]
demo里面 update操作不能更改NSInteger的数据

**Comment by netyouli** [comment]
已经升级更新，请更新代码
