### ISSUE TITLE
批量插入也是有点慢

### ISSUE THREAD

**Issue by jiangyunsheng** [netyouli/WHC_ModelSqliteKit#20]
利用inserts插入3000条简单的city数据就耗时2.383990秒，，，把三千条数据拆成100条插入一次，耗费的时间差不多，inserts最后还是跑到insert里边了，，跟自己调insert耗费时间差不多

**Comment by netyouli** [comment]
inserts和insert不是一个逻辑，inserts不是调的insert，如果方便希望你能发个demo我邮箱里我看看谢谢

**Comment by jiangyunsheng** [comment]
发自网易邮箱大师
在2017年03月08日 15:31，吴海超(WHC) 写道：

inserts和insert不是一个逻辑，inserts不是调的insert，如果方便希望你能发个demo我邮箱里我看看谢谢

**Comment by netyouli** [comment]
关于插入慢的问题已经找到并且修复了，请更新版本再试，并且支持复杂多表字段嵌套查询例如：NSArray * personArray = [WHC_ModelSqlite query:[Person class]
                                             where:@"name = '吴海超' and car.name = '宝马' or school.city.name = '北京'"];
