### ISSUE TITLE
关于查询的问题

### ISSUE THREAD

**Issue by xuzeyu** [netyouli/WHC_ModelSqliteKit#21]
感觉查询没那么方便耶，感觉用的最多的就是查询了，查询可以多元化一点么？或者说支持原生的sql语句。因为可能涉及多表或者多模型的查询删除等问题
例如demo项目中：

NSArray * personArray = [WHC_ModelSqlite query:[Person class] where:@"name != '吴海超'"];
我想查询的是person的car的name 等于 撼路者的
NSArray * personArray = [WHC_ModelSqlite query:[Person class] where:@"person.car.name = '撼路者'"];

就是 查询父类模型的继承属性的值 或 或者父类子类同时满足的条件，删除同理。。
希望可以支持复杂的查询。。。谢谢哈，个人意见仅供参考哈

**Comment by xuzeyu** [comment]
更新例子：
[WHC_ModelSqlite update:whc where:@"name = '吴海超2' OR age <= 18"];
如果我要更新继承属性的值， person的car的name 等于 撼路者的， 修改为 路虎，
那么
[WHC_ModelSqlite update:whc where: （@"name = '吴海超2' OR age <= 18"）];
括号内查询条件没法设置成 person.car.name = 撼路者

**Comment by netyouli** [comment]
我懂你的意思，这个以后会考虑加进去，谢谢

**Comment by xuzeyu** [comment]
本人还有点小疑问，想问下WHC_SqliteInfo的协议方法，弄成类别属性会不会好点？
例如Person类，修改版本号就是 person.version =@"1.0",
如果我在下一个实例person2存到第二版本，那就是person.version =@"2.0",
没设置的话就默认值统一存到 1.0版本。。
感觉现在是类方法，外部viewcontroll要修改模型版本号比较麻烦一点。
不知道我理解的对不对。。。。

**Comment by netyouli** [comment]
这样不行的，在多人开发的时候容易改乱，再就是person你是单个对象在进行批量存储的时候如果其中只有一个person.version = 1,其他person对象的version = 2这样就会出错的，WHC_SqliteInfo里的版本是针对Person这个类也就是表而不是表的某个记录（对象）

**Comment by netyouli** [comment]
库已经更新了，请更新最新版本，支持多表字段嵌套复杂查询NSArray * personArray = [WHC_ModelSqlite query:[Person class] where:@"person.car.name = '撼路者'"];

**Comment by xuzeyu** [comment]
好的，感谢

**Comment by huangzhibiao** [comment]
BGFMDB支持嵌套查询,可以去试试.
