### ISSUE TITLE
关于插入数据

### ISSUE THREAD

**Issue by yinjialiang1993** [netyouli/WHC_ModelSqliteKit#22]
我准备采用你的开源库，存储聊天消息.
我这边采用的是分页，每次只能存储20条，假若有很多条的话，我如何能更好的处理

1.第一进入 我请求20条完数据后，变成Model存入数据库,第一次这样，没问题.
2.第二次进入, 我再进入页面，现在其中有15条是已经缓存好的，还有5条是未读的.

我假若要用您的开源：我目前想到的是
找到我和那个人的聊天记录，找到最先一条，找到最后一条的时间，若>于这个时间的话，我再继续存.否则只读，但是我觉得这样不怎么友好...

我可能没看源码看的太仔细， 请问下我这样如何能更加友好的将这套框架 应用到我的聊天消息系统里面？

**Comment by netyouli** [comment]
其实你就当做普通的sqlite方式使用就行了，之前你怎么直接用sqlite插入数据，现在用我的库思路一样的，只不过我是对齐进行了封装而已，增删改查操作和传统方式一样的

**Comment by netyouli** [comment]
库已经更新了，请更新最新版本，支持多表字段嵌套复杂查询
