### ISSUE TITLE
怎么设置主键呢

### ISSUE THREAD

**Issue by MING10** [netyouli/WHC_ModelSqliteKit#23]
存储后更新，除了循环查找更新，有木有办法设置主键呢，存在即更新。

**Comment by netyouli** [comment]
自定义主键，demo里有示例代码，主键设置一次之后不允许更改了否则会出错

**Comment by MING10** [comment]
在model里设置主键可以。貌似不能用数据中带的key。怎么去重呢？

**Comment by netyouli** [comment]
你可以自定义主键的，只要顶自定义的不一样就是去重

**Comment by johann-wang** [comment]
在设置主键的时候,可以设置字段类型为text的吗?

**Comment by netyouli** [comment]
主键是int，可以你自行转换
