### ISSUE TITLE
怎么根据不用登陆的用户来建立不同的表文件夹呢?

### ISSUE THREAD

**Issue by xunan623** [netyouli/WHC_ModelSqliteKit#24]
就比如我现在a登陆请求的数据保存在a下面.这时切换账号b,那么b下面保存的表数据又是新数据

**Comment by netyouli** [comment]
在model里再添加一个用户名字段就行了，查询的时候用用户名去查询

**Comment by xunan623** [comment]
之前我采用的是一个登陆用户就新建用户的文件夹 这样不同用户的数据就能保存在不同文件夹下面,这样的存储是不是更加合理呢?

**Comment by netyouli** [comment]
这样也可以但是麻烦一些，你要根据用户名选取路径，而增加一个用户名字段查询的时候就where: @"userName = '登录名'"这样就行了，很简单的

**Comment by CoderBt** [comment]
想清空一个用户的所有数据会很麻烦。
