### ISSUE TITLE
是不是对JsonModel不支持

### ISSUE THREAD

**Issue by devkiang** [netyouli/WHC_ModelSqliteKit#25]
JsonModel的Array直接没存进去 。

**Comment by netyouli** [comment]
jsonmodel这是古董级别库了，jsonmodel好多自有属性我这库能存储继承类的属性所以不要用jsonmodel

**Comment by huangzhibiao** [comment]
BGFMDB可以,去试试看.

**Comment by netyouli** [comment]
fmdb本身没什么意义使用起来和直接使用sqlite api差不多唯独多了线程安全处理，基于fmdb的的封装更没意义，WHC_ModelSqlite使用最方便强大实用的数据库存储开源库

**Comment by huangzhibiao** [comment]
最强大？ 支持数组里存储不同的类型数据吗？ 支持存储NSHashTable，NSMapTable吗？

**Comment by huangzhibiao** [comment]
而且你存储自定义对象时还要实现NSCoding协议,多麻烦，多不直接.

**Comment by huangzhibiao** [comment]
还有你居然说FMDB本身没意义,你不也是使用sqlite api的么？！ 我还以为你是像微信那样是自己写的数据库结构文件！

FMDB，QQ和淘宝等这些大型的app都在用,你居然说没意义,你这就太无理取闹了😂.

**Comment by netyouli** [comment]
关于实现NSCoding目前随便哪个主流的json转Model开源库都支持一行代码实现，这个根本不是问题，也是因为这个我并没有在WHC_ModelSqlite重新搞一遍重复工作没意义，WHC_Model已经实现了。
至于你说的NSHashTable，NSMapTable，我写这么多年代码我就没从来没用过，我讲求实用，至于要支持更多数据类型这都是分分钟的事情，只不过我觉得目前的支持范围已经够用了，数组属性里面的元素类型随便因为数组属性是以data形式存在跟元素类型没关系

**Comment by netyouli** [comment]
呵呵我无理取闹？我和大众的观念不一样，我有我自己的判断，我不会因为大众都用什么我就认为它好或者怎么样，可能正因为我的无理取闹才贡献了这么多库，虽然star不多但是我认为值

**Comment by huangzhibiao** [comment]
不是star的问题，但是你不能说FMDB没意义，起码FMDB是经过亿万级别app考验的

**Comment by netyouli** [comment]
fmdb唯独稍微有使用价值就是操作sqlite是线程安全，以及取数据骚味比原生sqlite api要友好一点，但是还是要写很多重复代码，这样的东西在我眼里就是没有使用价值，我也从来没用过当然看过代码，呵呵你也别不服气，很多东西其实都是炒作起来的

**Comment by huangzhibiao** [comment]
我有什么不服气的😂,  你线程安全都不做,搞毛,刚测试存了1万数据,只给我存了200多条进去,你说别人是炒起来的,我该如何回答呢😂！

**Comment by huangzhibiao** [comment]
没有严谨性的框架，你说好还是不好？

**Comment by huangzhibiao** [comment]
其实BGFMDB就是我封装的,欢迎一起互找bug和缺陷.😂。
互相比较性能和功能,我没有恶意。

**Comment by netyouli** [comment]
WHC_ModelSqlite没线程安全处理？刚测试存了1万数据,只给我存了200多条进去，有这么垃圾？呵呵，既然如此就没有比较余地，你自己玩吧，我很忙

**Comment by huangzhibiao** [comment]
我还没有看你的源码，但是我存1万数据,真的只给我存了200多条进去,所以我只是猜你没有做线程安全处理造成了紊乱,我拍调试的照片给你看，骗你我是小狗.

**Comment by devkiang** [comment]
两个作者打起来的感觉，还是感谢！
