### ISSUE TITLE
可以用 SQL MAX() 函数么

### ISSUE THREAD

**Issue by 54dujianchao** [netyouli/WHC_ModelSqliteKit#26]
现有API 暂时 没想到 怎么实现

**Comment by netyouli** [comment]
目前版本还不支持sql max函数，以后会支持，敬请关注！

**Comment by netyouli** [comment]
最新版本可以使用max函数了，
`例如：NSNumber * maxAge = [WHCSqlite query:[Person class] func:@"max(age)"];`

**Comment by 54dujianchao** [comment]
想问下， 现有API，  可以 主键id自增长么

**Comment by netyouli** [comment]
主键是自增长的
