### ISSUE TITLE
如果自己不再做动作，都是主线程操作吗？

### ISSUE THREAD

**Issue by lijs11** [netyouli/WHC_ModelSqliteKit#28]
放在真机上突然很卡很卡.. 在view will appear 里写了这个

NSArray * personArray = [WHCSqlite query:[KKDataUps class] order:@"by interval desc"];

**Comment by netyouli** [comment]
如果数据很多查询要放到子线程里面

**Comment by lijs11** [comment]
再问一个问题      ！=      <>     字符串不等于 可以这样写吗？代码出来貌似都不对         

具体 delete where：  isSuccessed(参数1) = 1 AND  A(参数2)   <> ' 字符串 ' 

只要isSuccessed(参数1) = 1 执行了

**Comment by netyouli** [comment]
条件判断和sql标准语法一样
