### ISSUE TITLE
model 实现 WHC_SqliteInfo 协议出现一些问题

### ISSUE THREAD

**Issue by MrSongzj** [netyouli/WHC_ModelSqliteKit#30]
1.表里会多出4个字段：hash、superclass、debugDesciption、description。
2.删除属性会崩溃。报错信息如下：
`-[MSUser setHash:]: unrecognized selector sent to instance 0x60800002fde0`

原因应该是 WHC_SqliteInfo 协议继承了 NSObject 协议，NSObject 协议里定义了 hash、superclass、debugDesciption、description 这些属性，不过都是 readonly 的，所以再用旧数据来给新 model 设置值的时候出现上面错误信息。让 WHC_SqliteInfo 协议不继承 NSObject 协议应该就可以了。

然后感谢作者开源，看到了一个不一样的数据库处理方案。

**Comment by netyouli** [comment]
我表里怎么没有多着四个字段？

**Comment by MrSongzj** [comment]
我把 demo 和 sqlite 文件发给你，你看看我写的有没有问题。我是用 xcode 8.3 模拟器运行的


原始邮件
发件人:吴海超(WHC)notifications@github.com
收件人:netyouli/WHC_ModelSqliteKitWHC_ModelSqliteKit@noreply.github.com
抄送:mrsong424607870@qq.com; Authorauthor@noreply.github.com
发送时间:2017年4月10日(周一) 18:55
主题:Re: [netyouli/WHC_ModelSqliteKit] model 实现 WHC_SqliteInfo 协议出现一些问题 (#30)


我表里怎么没有多着四个字段？

**Comment by netyouli** [comment]
qq发给我

**Comment by MrSongzj** [comment]
424607870

**Comment by netyouli** [comment]
谢谢提醒，这个问题已经修复了，请更新
