### ISSUE TITLE
请问怎么查询本地已存在的数据库呢？

### ISSUE THREAD

**Issue by zhongfenglee** [netyouli/WHC_ModelSqliteKit#32]
大神，你好：
这个貌似是自己创建数据库，保存数据，再查询吧！
如果本地已经有了一个数据库，怎么查询该数据库呢？

**Comment by netyouli** [comment]
你需要把你自己以前创建的数据文件copy到library下的WHCSqlite下面并且把名称改为你model类名_1.0.sqlite这样就行了

**Comment by zhongfenglee** [comment]
能否详细说说你这个路径。刚开始用你这个框架，还不太熟悉。。。

**Comment by zhongfenglee** [comment]
可以增加这样一个接口：别把数据库路径写死，可以传进去已存在的数据库名字，即可进行查询。

**Comment by zhongfenglee** [comment]
大神，您好，应该是把数据库文件copy到library/Caches/WHCSqlite下后，将其改为你model类名_v1.0.sqlite，这样就可以查询到数据了
