### ISSUE TITLE
关于update的问题

### ISSUE THREAD

**Issue by BaiHan1989** [netyouli/WHC_ModelSqliteKit#33]
能不能根据条件update某一个字段的值，而不是全部清空？类似于sql语句
 //    BOOL result = [self.db executeUpdateWithFormat:@"update t_image set isUpload = %d where batch = %@",0,@"批次25"];

**Comment by netyouli** [comment]
目前不能

**Comment by netyouli** [comment]
新版本已经支持这个问题：
// 更新整条记录中指定的字段(更新Person表在age字段大于25岁时name值为whc，age为100岁)
    BOOL result = [WHCSqlite update:Person.self value:@"name = 'whc', age = 100"
                              where:@"age > 25"];
