### ISSUE TITLE
is there a way to insert or replace an object without adding it twice?

### ISSUE THREAD

**Issue by Sebacho-Barajas** [netyouli/WHC_ModelSqliteKit#34]
is there a way to insert or replace an object without adding it twice?
i don't want to  add the same objects twice but i need to update them,
example : I persisted some objects from my web service into the database, all objects have an ID , when I update my web service data I don't want to add those objects twice but update them

**Comment by netyouli** [comment]
if ([WHCSqlite update] == NO) {
   /// insert
   [WHCSqlite insert: updateModel];
}

**Comment by Sebacho-Barajas** [comment]
does this work while inserting an array of objects ?

**Comment by Sebacho-Barajas** [comment]
@netyouli any updates in this issue ? the answer you gave me didn't work!

**Comment by netyouli** [comment]
Insert the array model with WHCSqlite inserts API

**Comment by Sebacho-Barajas** [comment]
@netyouli  I already know I can do that but my question was on how to update an object without inserting it twice !

i suggest to create a method like this : 

+ (BOOL)insertOrUpdate:(id)model_object;

**Comment by netyouli** [comment]
我不是说了嘛？关于更新不存在你自己需要判断
if ([WHCSqlite update: model] == NO) { /// 更新失败
/// insert
      [WHCSqlite insert: updateModel];
}

**Comment by Sebacho-Barajas** [comment]
the method above didn't work for me :(

**Comment by Sebacho-Barajas** [comment]
@netyouli that didn't work for me :(

**Comment by netyouli** [comment]
哥们更新库啊试试，如果还有问题，麻烦发个重现demo我

**Comment by Sebacho-Barajas** [comment]
@netyouli  I have the latest update and still doesn't work , as I said you should implement a method like this `+ (BOOL)insertOrUpdate:(id)model_object;`it will check if an object already exists and update and if doesn't it will insert object

**Comment by netyouli** [comment]
哥们想多了，没有指定条件怎么去判断是否存在，再说这性能很差。
if ([WHCSqlite update: model] == NO) { /// 不存在
/// insert
[WHCSqlite insert: updateModel];
}

**Comment by Sebacho-Barajas** [comment]
i tried that, it will only add one object , as I told you i need to add multiple objects, i tried it with an array and still doesn't [WHCSqlite inserts:Array];

**Comment by huangshun11** [comment]
他应该是想要REPLACE语句
