### ISSUE TITLE
为什么是一个模型(一张表)存一个 sqlite 文件呢？

### ISSUE THREAD

**Issue by klaus01** [netyouli/WHC_ModelSqliteKit#37]
我一般的设计是一个 sqlite 数据库文件会存多个表，为什么这个库要一个表存一个 sqlite 文件呢？

有什么原因吗？

**Comment by netyouli** [comment]
用我的库就不要想按着你想的来，这样的设计主要为了独立管理model对应的数据库以及版本号

**Comment by klaus01** [comment]
另外建议 parserSubModelObjectFieldsWithModelClass 的数据做缓存处理，起麻批量插入相同模型的时候，parserSubModelObjectFieldsWithModelClass 只需要一次及可。

**Comment by netyouli** [comment]
这个没必要，移动端数据库操作以及表结构都不会很复杂，几乎感觉不出来差别，如果是解析json那是需要做缓存的

**Comment by CoderBt** [comment]
换登录用户的时候咋办。

**Comment by CoderBt** [comment]
换登录用户的时候，太麻烦了，暂时不考虑用了。

**Comment by klaus01** [comment]
@CoderBt 可以看下我这个修改版 https://github.com/klaus01/WHC_ModelSqliteKit

主要修改：
1. 不同的模型存一个数据库文件中，同样支持模型自动升级。
1. 可自定模型的表名，实现 whc_SqliteTableName 方法及可。

使用
``` objective-c
NSString *dataPath = [NSHomeDirectory() stringByAppendingPathComponent:@"/Documents/db.sqlite"];
WHC_ModelSqlite *db = [[WHC_ModelSqlite alloc] initWithFilePath:dataPath];
// 以下使用与原版一致
[db insert:...];
[db update:...];
[db delete:...]
```

**Comment by klaus01** [comment]
刚看到 WHC_ModelSqliteKit 1.2.5 已经支持自定义模型表名和迁移老数据库了。

**Comment by CoderBt** [comment]
但是想针对不同的用户使用不同的数据库，还是比较麻烦。我在看你的～
