### ISSUE TITLE
需求

### ISSUE THREAD

**Issue by JasonZhaoIos** [netyouli/WHC_ModelSqliteKit#38]
能新增自定义数据库名字和和数据库路劲吗?请回复谢谢.

**Comment by netyouli** [comment]
不支持，只能使用默认的

**Comment by netyouli** [comment]
升级功能：支持WHC_Sqlite操作使用其他方式创建的数据库比如FMDB
                  只需要指定数据库存储路径，如果表名不是模型类名称需要指定表名
                  支持自定义主键属性读取主键值不一定非要Model声明whcId属性
