### ISSUE TITLE
谢谢开源，并请教两个问题

### ISSUE THREAD

**Issue by xpsuper** [netyouli/WHC_ModelSqliteKit#4]
1、当模型的属性发生变化（如增加、减少、更名）时，是否有方法进行数据迁移（将变化之前已存储的数据直接通过某种规则迁移至新的模型结构中，迁移规则可借鉴 realm 直接已 block 交给业务方）？

2、是否需要业务方自己处理多线程资源竞争问题？

**Comment by netyouli** [comment]
你如果有这两个疑问说明你根本还没深入了解本项目，模型属性的删除或者增加只需要修改model类的VEASION方法版本号即可也是github所说智能数据库字段更新机智，这库会自动进行数据库更新字段并保留历史记录，该项目是线程安全不存在资源竞争问题
