### ISSUE TITLE
已解决！加密问题

### ISSUE THREAD

**Issue by megabes** [netyouli/WHC_ModelSqliteKit#40]
WHC_ModelSqlite.m文件中：
561行：
`        if (![self setKey:is_update_psw ? old_psw : psw_key]) {
`
应该是：
`        if (![self setKey:is_update_psw ? psw_key : old_psw]) {
`

**Comment by netyouli** [comment]
没有错误，请认真阅读逻辑

**Comment by megabes** [comment]
仔细看了代码，确实我弄错了。已解决！=
