### ISSUE TITLE
怎么创建联合主键

### ISSUE THREAD

**Issue by johann-wang** [netyouli/WHC_ModelSqliteKit#41]
创建数据库时候,需要使用到联合主键,请问如何设置

**Comment by netyouli** [comment]
/// 自定义数据表主键名称
/**
*** 返回自定义主键名称默认主键:_id ***
*/
+ (NSString *)whc_SqliteMainkey;

然后再模型声明这样一个主键属性即可

**Comment by johann-wang** [comment]
很高兴你能这么快回复我.我这里需要设置两个主键,一个字段是integer,另外一个字段是text类型
我这里在模型类的.m中加上了+ (NSString *)whc_SqliteMainkey {
    return @"userId";
}
然后在.h中添加了相应的属性@property (nonatomic, strong) NSString *userId;
这样得到的主键只有一个,而且只能是integer

**Comment by netyouli** [comment]
主键只能是int类型，如果你要一个text，你可以这样声明:
@property (nonatomic, assgin) int *userId;
@property (nonatomic, strong，readonly) NSString *textId; 然后实现m文件里get方法return @(userld).stringValue;
希望能帮到你

**Comment by johann-wang** [comment]
明白.这里相当于作了一次映射.这种方法可能不适用我目前的情况.谢谢你的帮助
