### ISSUE TITLE
数据更新问题

### ISSUE THREAD

**Issue by zhoujun706** [netyouli/WHC_ModelSqliteKit#46]
+ (BOOL)update:(id)model_object where:(NSString *)where;

我想要更新这个模型还需要加上条件语句，而条件语句查询出来的可能不止一条，这样就会更新到不需要更新的数据了

**Comment by netyouli** [comment]
是的，所以你的where条件必须要写的准确哦

**Comment by zhoujun706** [comment]
嗯嗯，谢谢
