### ISSUE TITLE
关于demo的线程安全测试问题

### ISSUE THREAD

**Issue by c-ys** [netyouli/WHC_ModelSqliteKit#48]
demo中，线程1存储的name为武汉，为什么断点看到插入的3个数据都是北京呢

**Comment by netyouli** [comment]
因为线程异步的，先执行了下面的name赋值语句

**Comment by c-ys** [comment]
thx，懂了，线程异步，多个赋值语句都先执行，因为是对一个对象的属性赋值，所以插入时候数据都一样

**Comment by netyouli** [comment]
shi de
