### ISSUE TITLE
whc_SqlitePath问题

### ISSUE THREAD

**Issue by LDXu** [netyouli/WHC_ModelSqliteKit#50]
使用很久了，今天看了一下库发现这个新功能，测试一下，感觉使用有点问题？
1.+ (NSString *)whc_SqlitePath方法是定义了一个绝对路径，WHC_ModelSqliteKit能否提供默认目录的API,返回xxxxx/Library/Caches/WHCSqlite/，然后去拼接？
猜测该协议使用场景一般只是为了区分多用户添加一个目录(Library/Caches/WHCSqlite/uid/)，数据库存目录不用太分散，为了更适用应该是绝对路径，只是最好提供一个默认路径，使用者不需要去看原来数据库存放地址Library/Caches/WHCSqlite/uid/UserModelClass
2.使用whc_SqlitePath时，如果已有数据库的话，使用者需要处理迭代更新时，转移到指定目录。能否返回一个字典@{newPath:oldPath}?
+ (NSString *)databaseCacheDirectory:(Class)model_class的时候（这个库查找模型数据库目录的时候都用调用这个吧？）去处理移动，但是现在移动的时候有个问题（xxxxx/Library/Caches/WHCSqlite/Person_v1.0.0.sqlite）。这个方法改动的话，我无法找到原来的库路径，因为版本查询也调用。我想了一个方法，查找所有旧目录的文件，_v分割字符串？移动后名称还是原版本号，版本号逻辑版本号的协议方法去改。
不知道这样对不对

**Comment by netyouli** [comment]
是有默认路径，+ (NSString *)whc_SqlitePath 这个方法只是给原来使用fmdb或者手工创建数据库做支持的，默认不需要实现这个协议方法的

**Comment by netyouli** [comment]
+ (NSString *)whc_SqlitePath是绝对路径，因为之前收到有人说想自定义路径放到其他路径下面所以就有这个方法，这个版本号查询没有关系，只要自定义了路径，后面相关操作都是会优先自定义路径来查询然后才是默认路径的。所以没有关系的
`+ (NSString *)databaseCacheDirectory:(Class)model_class {
    if (model_class) {
        NSString * custom_path = [self exceSelector:@selector(whc_SqlitePath) modelClass:model_class];
        if (custom_path != nil && custom_path.length > 0) {
            return custom_path;
        }
    }
    return [NSString stringWithFormat:@"%@/Library/Caches/WHCSqlite/",NSHomeDirectory()];
}`

**Comment by LDXu** [comment]
第一个问题是涉及到路径
第二个问题是涉及数据迁移，返回一个字典自动迁移文件，具体看下提交的，不知道那样处理是否正确

**Comment by LDXu** [comment]
要迁移的吧，以前就使用这个数据的话，都存在默认目录上，自定义以后都是去自定义的路径查找了，需要把原文件移动到自定义目录里面

**Comment by netyouli** [comment]
哦你说这个，理论上是的
