### ISSUE TITLE
关于whc_SqlitePasswordKey加密后 无法查看问题

### ISSUE THREAD

**Issue by FuckUmei** [netyouli/WHC_ModelSqliteKit#55]
按照流程添加了pod 'WHC_ModelSqliteKit/SQLCipher'  确实加密成功了。。
但是导出数据库文件。。用SQLiteManager和SQLiteProfessional这些GUI工具都不无法查看。。
输入密钥后总是提示错误。。请问外部如何查看呢？

**Comment by FuckUmei** [comment]
标题错了。。是 “ whc_SqlitePasswordKey”

**Comment by netyouli** [comment]
外部查看加密数据库要输入密码的

**Comment by FuckUmei** [comment]
ok 感谢。。已经解决。。使用 DB Browser for SQLite 可以打开。。
