### ISSUE TITLE
自定义数据库路径查询不到数据

### ISSUE THREAD

**Issue by c-ys** [netyouli/WHC_ModelSqliteKit#57]
在使用过程中，因业务需求，需要存储不同用户的数据，退出不能清空所有数据。

      使用+ (NSString *)whc_SqlitePath;方法定义不同用户的存储路径。

      但是使用后，发现查询不到数据。库介绍中，修复升级: 支持自定义数据库存储路径，所以想向作者确认下，v1.3版本的代码是最新的，已经修复了这个问题了吗？

**Comment by netyouli** [comment]
不需要的你可以在原来的模型类里面添加一个username属性即可，然后更新一下数据库的版本号就行了
