### ISSUE TITLE
如果加入新字段 保存失败

### ISSUE THREAD

**Issue by huangping35** [netyouli/WHC_ModelSqliteKit#61]
例如今天user这个对象添加了一个新字段，nick_name 如果保存就失败，请问要怎么做？

**Comment by huangping35** [comment]
解决了，谢谢

**Comment by LukiWen** [comment]
如何解决的？

**Comment by huangping35** [comment]
> 如何解决的？

/// 自定义模型类数据库版本号
/** 注意：
 ***该返回值在改变数据模型属性类型/增加/删除属性时需要更改否则无法自动更新原来模型数据表字段以及类型***
 */

+(NSString *)whc_SqliteVersion
{
    NSDictionary *infoDictionary = [[NSBundle mainBundle] infoDictionary];
      // app版本
   NSString *app_Version = [infoDictionary objectForKey:@"CFBundleShortVersionString"];

   // app build版本

   NSString *app_build = [infoDictionary objectForKey:@"CFBundleVersion"];

   
    return [app_Version stringByAppendingString:app_build];
    
}
