### ISSUE TITLE
和 Realm 有什么差别呢？

### ISSUE THREAD

**Issue by Huang-Libo** [netyouli/WHC_ModelSqliteKit#7]
看了 Read me 中的基本用法，和 Realm 一样简便，请问和 Realm 的差别主要在哪些方面呢？

**Comment by netyouli** [comment]
realm我不了解，我只知道我这目前是世界上iOS使用最简单功能最强大的数据库框架，虽然star不多，主要是很多人不太相信可以有这么强大，但是慢慢我相信会被大家意识到，你可以仔细看看比较比较就知道了

**Comment by Huang-Libo** [comment]
建议你看一下 [Realm](https://github.com/realm/realm-cocoa) ，你可能会发现这个牛x的事情已经有人做了…

**Comment by tigerandy163com** [comment]
和 LKDBHelper 有什么区别呢，能比较的说一下你的优势吗

**Comment by Jinxiansen** [comment]
讲真，一看到 [WHC_ModelSqlite removeAllModel];  这种方法还带这么长的前缀还带下划线，我都没有看download 的兴趣了。
道友还敢自诩：目前是世界上iOS使用最简单功能最强大的数据库框架 
这句话我只看看，不说话。

**Comment by netyouli** [comment]
LKDBHelper我不了解，所以区别和优势只能靠你自己去发现了，谢谢

**Comment by Jinxiansen** [comment]
Realm 你不了解，LKDBHelper 你不了解，
那么我想问一句，你凭什么自诩：我这目前是世界上iOS使用最简单功能最强大的数据库框架 ？？？
坐井观天？

**Comment by netyouli** [comment]
哥们别激动不至于，我自己写的项目我自己认为最好的这是很正常的，你觉得我说的不对，你完全可以无视该项目，谢谢

**Comment by nandock** [comment]
不错

**Comment by huangzhibiao** [comment]
妈的,我看不下去了,我来说句公道话,Realm不支持集合的直接存储,LKDBHelper(这个就是渣,群主都被我踢馆了)不支持数组里面存储不同的自定义类型，目前就BGFMDB和这个框架支持！没有深入了解过的,他妈别来装逼,我看不下去了😂。

**Comment by huangzhibiao** [comment]
Realm的唯一优势就是比sqlite的存取速度快一点。
