### ISSUE TITLE
有swift版本吗？

### ISSUE THREAD

**Issue by baoLianD** [netyouli/WHC_ModelSqliteKit#8]

**Comment by netyouli** [comment]
目前没有

**Comment by megabes** [comment]
swift版本和C兼容不好，swift和OC混编很方便，目前项目就是混编，用了WHC_ModelSqliteKit

**Comment by Runyalsj** [comment]
查询条件怎么作为参数查找

**Comment by netyouli** [comment]
[whcsqlite query: [nsstring stringwithfromat:@"age = %d", age]];
